config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'pages/home'
  get 'pages/perfil'
  get 'pages/troll'
  get 'pages/admin'
  get 'products/index'
  get 'products/condimentos'
  get 'products/cafedamanha'
  get 'products/carros'
  get 'products/findcategory'
  get 'products/addtocart'
  get 'products/search'
  get 'products/new'
  get 'carrinho/show' => 'carrinho#show'
  resources :categories
  resources :products
  resources :orders

  get 'orders/details/:id' => 'orders#detail'
  post 'orders/alterstatus'
  get 'carts/limpar'
  get 'carts/addtocart'
  get 'carts/aumentarqtd'
  get 'carts/diminuirqtd'
  get 'carts/destroy'
  post 'carts/destroy'
  get 'carts/remove'
  get 'carts/rise'
  get 'carts/low'
  post 'carts/rise'
  post 'carts/low'
  post 'carts/show' => 'carts#show'
  resources :carts,only: [:show]
  get 'users/new'
  resources :users

  get 'pages/home'
  root 'pages#home'
	get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :protegories, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :require_current_user,only: [:show]
	before_action :require_admin,only: [:index]


	def index
		if(params[:order] == nil)
			@orders = Order.all.order("id ASC")
		else	
			@orders = Order.all.order("#{params[:order]} ASC")
		end
		@status = Status.all
	end

	def show
		@orders = Order.where(:owner_id => params[:id])
		@user = User.find(current_user)

	end
	def new
		@orders = Order.new
	end

	def create #criar um pedido novo
		@orders = Order.new
		current_cart
		@total = 0
		current_cart.each do |h|
			@total += h["quantity"]*h["price"]
		end
		@total

		@orders.owner_id = (params[:owner_id])
		@orders.total = @total
		@orders.status = (params[:status])
		@orders.deliverydate = (params[:date])
		@orders.items = current_cart
		if @orders.save
			flash[:success] = "Pedido Realizado!"
	  		redirect_to order_path(current_user.id)
  		else
  		
  		end
	end

	def detail
		@order = Order.find(params[:id])
		@user = User.find(@order.owner_id)
		
		@products = []
		@order.items.each do |h|
			pr = Product.find(h["product_id"])
			@products << pr.name
		end
		@products
	end

	def alterstatus
		@order = Order.find(params[:id])
		@order.status = (params[:status])
		@order.save
		redirect_to :back
	end

	private 
	def order_params
  		params.require(:orders).permit(:owner_id)
  	end
  	def require_admin
  		if (!logged_in?) or (logged_in? and !current_user.admin?)
  			flash[:danger] = "So admins podem fazer isso"
  			redirect_to root_path
  		end
  	end
	def require_current_user
		if (!logged_in?) or (params[:id] != current_user.id.to_s) and !current_user.admin?
			flash[:danger] = "Você só pode ver suas compras"
  			redirect_to root_path
  		end	
	end
end	

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/detail.html.erb
<h1>Detalhes do pedido número <%= @order.id %></h1>
<% if current_user.admin? %>
<p>Usuário: <%= @user.name %></p>
<% end %>
<table>
	
	

</table>	
<table class="table table-hover">
     <thead >
       <tr>
         <th>Nome</th>
         <th>Total</th>
         <th>Quantidade</th>
       </tr>
     </thead>
     <tbody>
       <% @order.items.each_with_index do |h,idx| %>
		<tr>
			<td><%= @products[idx] %></td>
			<td>R$ <%= '%.2f'%((h["quantity"].to_f)*(h["price"].to_f)) %></td>
			<td><%= h["quantity"] %></td>

		</tr>

		<% end %>
    </tbody>
</table>

<p>Total: R$ <%= '%.2f'%(@order.total) %></p>
<% if current_user.admin? %>
<p>Data do pedido: <%= @order.created_at %></p>
<%= link_to 'Voltar',orders_path,class: "btn btn-primary" %>
<% else %>
<%= link_to 'Voltar',order_path(current_user) ,class: "btn btn-primary" %>
<% end %>

app/views/orders/index.html.erb
<h1>Pedidos Realizados</h1>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Ordenar
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to 'Status', orders_path(order: "status") %></li>
    <li><%= link_to 'ID', orders_path(order: "id") %></li>
    <li><%= link_to 'ID Pedidor', orders_path(order: "owner_id") %></li>
    <li><%= link_to 'Total', orders_path(order: "total") %></li>
  </ul>
</div>
<table class="table table-hover">
  <thead >
       <tr>
         <th>Numero do Pedido</th>
         <th>Numero do ID do Pedidor</th>
         <th>Data de Entrega</th>
         <th>Total</th>
         <th>Status</th>
         <th>Detalhes</th>
       </tr>
     </thead>
     <tbody>
    <% @orders.each do |x| %>
      <tr>
        <td><%= x.id %></td>
        <td><%= x.owner_id %></td>
        <td><%= x.deliverydate %></td>
        <td>R$ <%= '%.2f'%(x.total) %></td>
        <td><% message = Status.find(x.status).name %>
        <% if x.status == 1 %>
                <% tatus = 'warning' %>
               
              <% else if x.status == 2 %>
               
                  <% tatus = 'success' %>
                <% else if x.status == 3%>
               
                  <% tatus = 'danger' %>
                <% else %>
                  <% tatus = 'primary' %>
              <% end %>
              <% end %>
        <% end %>
          <div class="dropdown">
            <button class="btn btn-<%= tatus %> dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= message %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <% @status.each do |s| %>
                  <% if s.id == 1 %>
                    <% tatus = 'warning' %>
                   
                  <% else if s.id == 2 %>
                   
                      <% tatus = 'success' %>
                    <% else if s.id==3 %>
                   
                      <% tatus = 'danger' %>
                      <% else %>
                        <% tatus = 'primary' %>
                    <% end %>
                    <% end %>
                  <% end %>
                  <li><%= link_to s.name,orders_alterstatus_path(id: x.id, status: s.id),remote: true,method: "POST",class: "btn btn-#{tatus}" %></li>
                <% end %>
            </ul>
          </div>
        </td>
        <td><%= link_to '<i class="glyphicon glyphicon-new-window"></i>'.html_safe,'/orders/details/'+ x.id.to_s, class: "btn btn-primary" %></td>
      </tr>       
      <% end %>
     </tbody>
</table>

app/views/orders/show.html.erb
<h1>Pedidos  de <%= @user.name %></h1>
<table class="table table-hover">
	<thead >
       <tr>
         <th>Numero do Pedido</th>
         <th>Data de Entrega</th>
         <th>Total</th>
         <th>Status</th>
         <th>Atualizado em</th>
         <th>Detalhes</th>
       </tr>
     </thead>
     <tbody>
		<% @orders.each do |x| %>
			<tr>
				<td><%= x.id %></td>
				<td><%= x.deliverydate %></td>
				<td>R$ <%= '%.2f'%(x.total) %></td>
				<td><% if x.status == 1 %>
					<input type="text" class="btn btn-warning disabled" value="<%= Status.find(x.status).name %>" style="text-align: center" readonly/>
					<% else if x.status == 2 %>
					<input type="text" class="btn btn-success disabled" value="<%= Status.find(x.status).name %>" style="text-align: center" readonly/>
					<% else if x.status == 3 %>
						<input type="text" class="btn btn-danger disabled" value="<%= Status.find(x.status).name %>" style="text-align: center" readonly/>
					<% else %>
						<input type="text" class="btn btn-primary disabled" value="<%= Status.find(x.status).name %>" style="text-align: center" readonly/>
					<% end %>
					<% end %>
					<% end %>
				</td>
				<td><%= x.updated_at %></td>
				<td><%= link_to '<i class="glyphicon glyphicon-new-window"></i>'.html_safe,'/orders/details/'+ x.id.to_s, class: "btn btn-primary" %></td>
			</tr>     	
     	<% end %>
     </tbody>
</table>