config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'pages/home'
  get 'pages/perfil'
  get 'pages/troll'
  get 'pages/admin'
  get 'products/index'
  get 'products/condimentos'
  get 'products/cafedamanha'
  get 'products/carros'
  get 'products/findcategory'
  get 'products/addtocart'
  get 'products/search'
  get 'products/new'
  get 'carrinho/show' => 'carrinho#show'
  resources :categories
  resources :products
  resources :orders

  get 'orders/details/:id' => 'orders#detail'
  post 'orders/alterstatus'
  get 'carts/limpar'
  get 'carts/addtocart'
  get 'carts/aumentarqtd'
  get 'carts/diminuirqtd'
  get 'carts/destroy'
  post 'carts/destroy'
  get 'carts/remove'
  get 'carts/rise'
  get 'carts/low'
  post 'carts/rise'
  post 'carts/low'
  post 'carts/show' => 'carts#show'
  resources :carts,only: [:show]
  get 'users/new'
  resources :users

  get 'pages/home'
  root 'pages#home'
	get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :protegories, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	acts_as_shopping_cart_using :cart_item
	#comentario aleatorio
	#outro comentario
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	

	def addtocart
		#cart = current_cart
		@products = Product.find(params[:product])
		if (!current_cart.empty? && current_cart.any?{|h| h["product_id"] == @products.id})
			flash[:danger] = "Produto já consta no carrinho"
		else
			current_cart << {product_id: @products.id,quantity: 1,price: @products.price}
			flash[:success] = "Produto adicionado"
		end
		redirect_to :back
	end
	def remove
		@products = Product.find(params[:product])
		current_cart.delete_if{|h| h["product_id"] == @products.id}

		redirect_to carts_show_path
	end

	def rise
		@product = Product.find(params[:product])
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		h["quantity"] += 1
		 	end
		end
		respond_to do |format|
			format.html{ redirect_to carts_show_path}
			
			format.js
		end
		#redirect_to carts_show_path
		
	end
	def low
		@product = Product.find(params[:product])
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		if h["quantity"] != 0
		 			h["quantity"] -= 1
		 		end
		 	end
		end
		respond_to do |format|
			format.html{ redirect_to carts_show_path}
			
			format.js
		end
		#redirect_to carts_show_path
		
	end

	def destroy
		current_cart.clear
		redirect_to carts_show_path
	end

	def show
		@products = []
		if (!current_cart.empty?)
			current_cart.each do |h|
				pr = Product.find(h["product_id"])
				@products << {:id => pr.id,:name => pr.name,:description => pr.description,:price => pr.price,:quantity => h["quantity"]}
				#@products << h["product_id"]
			end
		end
		@cart = current_cart
		@total = 0
		current_cart.each do |h|
			@total += h["quantity"]*h["price"]
		end
		@total
	end
end

app/helpers/carts_helper.rb
module CartsHelper

    def current_cart
        session[:cart] ||= []
    end
	def rise(idd)
		@product = Product.find(idd)
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		h["quantity"] += 1
		 	end
		end
	end
    
end

app/views/carts/low.js.erb
$(document).ready(function(){
	console.log("pudim");
	var id = <%= params[:product] %>;
	var quantidade = parseInt($('#fieldQt'+id).val());
	var preco = <%= params[:prc] %>
	var tot = parseFloat($('#total').val());
	tot -= preco;
	if (quantidade != 0){	
		quantidade -= 1;
	}
	tot = tot.toFixed(2);
	console.log("ola");
	$('#fieldQt'+id).val(quantidade);
	$('#priceQty'+id).val((quantidade*preco).toFixed(2));
	$('#total').val(tot);
});

app/views/carts/rise.js.erb
$(document).ready(function(){
	console.log("pudim");
	var id = <%= params[:product] %>;
	var quantidade = parseInt($('#fieldQt'+id).val());
	var preco = <%= params[:prc] %>;
	var tot = parseFloat($('#total').val());
	quantidade += 1;
	tot += preco;
	tot = tot.toFixed(2);
	$('#fieldQt'+id).val(quantidade);
	$('#priceQty'+id).val((quantidade*preco).toFixed(2));
	$('#total').val(tot);
		

});

app/views/carts/show.html.erb
<h1>Carrinho</h1>

<!--
<table class="table table-hover">
     <thead >
       <tr>
         <th>Nome</th>
         <th>Preço</th>
         <th>Quantidade</th>
         <th>Alterar</th>
       </tr>
     </thead>
     <tbody>
       <% @products.each_with_index do |i,idx| %>
         <tr>
           <td>  <%= i[:name] %></td>
           <td>R$<input type="text" id="priceQty<%= i[:id]%>" class="fieldQty" value="<%= i[:quantity] * i[:price]%>" style="text-align: center" size="6" readonly/>
            </td>
           <td>
               <input type="text" id="fieldQt<%= i[:id]%>" class="fieldQty" value="<%= i[:quantity]%>" style="text-align: center" size="3" readonly/>
            </td>
            <td>
               <%= link_to '<i class="glyphicon glyphicon-minus"></i>'.html_safe,carts_low_path(:product  => i[:id],qtd: i[:quantity],prc: i[:price],posicao: idx),remote: true,id: 'btnMinus'+i[:id].to_s,class: "btn btn-danger" %>
               <%= link_to '<i class="glyphicon glyphicon-plus"></i>'.html_safe,carts_rise_path(:product  => i[:id],qtd: i[:quantity],prc: i[:price],posicao: idx),remote: true,id: 'btnPlus'+i[:id].to_s,class: "btn btn-success" %>
            </td>
           <td><%=link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe,{:controller => "carts", :action => "remove",:product => i[:id]},class: "btn btn-primary" %></td>
           
         </tr>
      <%end%>
    </tbody>
</table>-->

<div class="container">
  
  <% @products.each_with_index do |i,idx| %>
    <div class="product_square col-md-3">
    <img src="http://worldartsme.com/images/shop-cart-icon-clipart-1.jpg" />
           <h3>  <%= i[:name] %></h3>
           <p>Quantidade
               <input type="text" id="fieldQt<%= i[:id]%>" class="fieldQty" value="<%= i[:quantity]%>" style="text-align: center" size="3" readonly/>
            </p>
           <div align="right">R$ <input type="text" id="priceQty<%= i[:id]%>" class="fieldQty" value="<%= i[:quantity] * i[:price]%>" style="text-align: center" size="6" readonly/>
            </div>
           
            <p>
               <%= link_to '<i class="glyphicon glyphicon-minus"></i>'.html_safe,carts_low_path(:product  => i[:id],qtd: i[:quantity],prc: i[:price],posicao: idx),remote: true,id: 'btnMinus'+i[:id].to_s,class: "btn btn-danger" %>
               <%= link_to '<i class="glyphicon glyphicon-plus"></i>'.html_safe,carts_rise_path(:product  => i[:id],qtd: i[:quantity],prc: i[:price],posicao: idx),remote: true,id: 'btnPlus'+i[:id].to_s,class: "btn btn-success" %>
            </p>
           <p><%=link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe,{:controller => "carts", :action => "remove",:product => i[:id]},class: "btn btn-primary" %></p>
           
  </div>       
      <%end%>
  
</div>

<p>Total: R$<input type="text" size="6" id="total" class="fieldQty" value="<%= @total %>" style="text-align: center" size="2" readonly/></p>
<%=link_to 'Esvaziar Carrinho',{:controller => "carts", :action => "destroy"},class: "btn btn-primary" %>
<% if logged_in? %>
<%=link_to 'Finalizar Compra',orders_path(owner_id: current_user.id,status: 2,date: Date.today),method: "POST",data:{confirm: "Quer mesmo finalizar a compra?"}, class: "btn btn-primary" %>
<% else %>
<%= link_to 'Entre para Finalizar',sign_in_path,class: "btn btn-primary" %>
<% end %>
<br>