config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'pages/home'
  get 'pages/perfil'
  get 'pages/troll'
  get 'pages/admin'
  get 'products/index'
  get 'products/condimentos'
  get 'products/cafedamanha'
  get 'products/carros'
  get 'products/findcategory'
  get 'products/addtocart'
  get 'products/search'
  get 'products/new'
  get 'carrinho/show' => 'carrinho#show'
  resources :categories
  resources :products
  resources :orders

  get 'orders/details/:id' => 'orders#detail'
  post 'orders/alterstatus'
  get 'carts/limpar'
  get 'carts/addtocart'
  get 'carts/aumentarqtd'
  get 'carts/diminuirqtd'
  get 'carts/destroy'
  post 'carts/destroy'
  get 'carts/remove'
  get 'carts/rise'
  get 'carts/low'
  post 'carts/rise'
  post 'carts/low'
  post 'carts/show' => 'carts#show'
  resources :carts,only: [:show]
  get 'users/new'
  resources :users

  get 'pages/home'
  root 'pages#home'
	get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :protegories, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :protegories
	has_many :categories, through: :protegories
	validates :name,presence: true, length: {maximum: 50}
	validates :price,presence: true
	validates :description, presence: true
	def self.search(search)
	  where("name ILIKE ?", "%#{search}%") 
	  #where("content LIKE ?", "%#{search}%")
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :require_admin, only: [:new,:create, :edit,:update]

	def show

	end
	def index
		if(params[:order] == nil)
			@products = Product.all.order("id ASC")
		else	
			if params[:order] == 'pricemaior'
				x = 'DESC'
				params[:order] = 'price'
			else
				x = 'ASC'
			end
			@products = Product.all.order("#{params[:order]} "+x)
		end
		
	end
	def new
		@product = Product.new
	end

	def create
		@product = Product.new(products_params)
		if @product.save
			params[:categorias].each do |cat|
				catigo = Category.find_by(name: cat)
				@protegory = Protegory.new(category_id: catigo.id,product_id: @product.id)
				@protegory.save
			end
			redirect_to pages_admin_path
  			flash[:success] = "Produto criado"
 	 	else
  			render action: :new

  		end
	end

	def edit
		@product = Product.find(params[:id])
	end
	def update
      @product = Product.find(params[:id]) 
      if @product.update_attributes(products_params)
        redirect_to pages_admin_path
        flash[:success] = "Produto Atualizado"
      else
        render action: :edit
      end
  	end

	def condimentos
		@products = Product.joins(:categories).where(:categories => {:name => "condimentos"})
	end
	def cafedamanha
		@products = Product.joins(:categories).where(:categories => {:name => "cafedamanha"})
	end
	def carros
		@products = Product.joins(:categories).where(:categories => {:name => "carros"})
	end

	def get
		#redirect_to products_search_path
	end
	
	def findcategory
		@products = Product.joins(:categories).where(:categories => {:name => params[:categoryname]})
		if(params[:order] == nil)
			@products.order("id ASC")
		else	
			if params[:order] == 'pricemaior'
				x = 'DESC'
				params[:order] = 'price'
			else
				x = 'ASC'
			end
				@products = @products.order("#{params[:order]} "+x)
		end
	end

	def search
		@products = Product.all
		  if params[:search]
		    @products = Product.search(params[:search]).order("created_at DESC")
		  else
		    @products = Product.all.order('created_at DESC')
		  end
	end
	
	private
		def search_page
			redirect_to products_search_path
		end

		def products_params
  			params.require(:product).permit(:name, :description, :price,:sellable)
  		end
  		def require_admin
  			if (!logged_in?) or (logged_in? and !current_user.admin?)
  				flash[:danger] = "So admins podem fazer isso"
  				redirect_to root_path
  			end
  		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_formproducts.html.erb
<div class="row">
  <div class="col-md-12">

  <%= form_for @product do |f| %>
              <% if @product.errors.any? %>
              <div id="error_explanation">
                          <div class="alert-error">
                                     <p>O formulário contém <%= pluralize(@product.errors.count, "erro") %>.</p>
                          </div><br>
                          <ul class="list-group">
                                     <% @product.errors.full_messages.each do |msg| %>
                                     <li class="list-group-item list-group-item-danger"><%= msg %></li>
                                     <% end %>
                          </ul>
              </div>
  <% end %>
              <div class="form-group">
                          <%= f.label :name %>
                          <%= f.text_field :name,class: "form-control",placeholder: "Nome" %>
              </div>
              
              <div class="form-group">
                          <%= f.label :description %>
                          <%= f.text_area :description,class: "form-control",placeholder: "Descricao" %>
              </div>
              

              <div class="form-group">
                          <%= f.label :price %>
                          <%= f.number_field :price,class: "form-control",step: :any,min: 0,placeholder: "xx,yy" %>
              </div>
              <div class="form-group">
                          <%= f.label :sellable? %><br>
                          <%= f.check_box :sellable,class: "form-check-in" %>
              </div>
              <div class="form-group">
                          <%= f.label :categories %><br>  
                          <% categories.each do |cat| %>
                            <% botao = "danger" %>
                            <% @product.categories.each do |ctg|%>
                              <% if ctg.name == cat.name %>
                                <% botao = "success" %>
                              <% end %>
                            <% end %>
                          <% if botao == "danger" %>
                            <%= link_to cat.name.capitalize,protegories_path(cat_id: cat.id,pro_id: @product.id),method: :post,remote: true,class: "btn btn-#{botao}" %>
                          <% else %>
                            <%= link_to cat.name.capitalize,protegory_path(cat_id: cat.id,pro_id: @product.id),method: :delete,remote: true,class: "btn btn-#{botao}" %>
                          <% end %>
                          <% end %>
                      
              </div>
              <div class="actions">
                          <%= f.submit "Enviar",class: "btn btn-primary"%>
              </div>
  <% end %>
  </div>
</div>

app/views/products/_formproducts2.html.erb
<div class="row">
  <div class="col-md-12">

  <%= form_for @product do |f| %>
              <% if @product.errors.any? %>
              <div id="error_explanation">
                          <div class="alert-error">
                                     <p>O formulário contém <%= pluralize(@product.errors.count, "erro") %>.</p>
                          </div><br>
                          <ul class="list-group">
                                     <% @product.errors.full_messages.each do |msg| %>
                                     <li class="list-group-item list-group-item-danger"><%= msg %></li>
                                     <% end %>
                          </ul>
              </div>
  <% end %>
              <div class="form-group">
                          <%= f.label :name %>
                          <%= f.text_field :name,class: "form-control",placeholder: "Nome" %>
              </div>
              
              <div class="form-group">
                          <%= f.label :description %>
                          <%= f.text_area :description,class: "form-control",placeholder: "Descricao" %>
              </div>
              

              <div class="form-group">
                          <%= f.label :price %>
                          <%= f.number_field :price,class: "form-control",step: :any,min: 0,placeholder: "xx,yy" %>
              </div>
              <div class="form-group">
                          <%= f.label :sellable? %><br>
                          <%= f.check_box :sellable,class: "form-check-in" %>
              </div>
              <div class="form-group">
                        <h4>Categorias</h4>
                        <ul>  
                          <% categories.each do |cat| %>
                            <li><%=cat.name.capitalize%> <%= check_box_tag 'categorias[]',cat.name,false,class: "form-check-in" %></li>
                          <% end %>
                        </ul>  
              </div>
              
              <div class="actions">
                          <%= f.submit "Enviar",class: "btn btn-primary"%>
                          
              </div>
  <% end %>
  </div>
</div>

app/views/products/_productsform.html.erb
<div class="dropdown" style="display:inline">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Categorias
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% categories.each do |cat| %>
        <li><%= link_to cat.name.capitalize,products_findcategory_path(categoryname: cat.name) %></li>  
    <% end %>
  </ul>
</div>
<div class="dropdown" style="display:inline">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Ordenar
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to 'Preço Maior', products_findcategory_path(order: "pricemaior",categoryname: params[:categoryname]) %></li>
    <li><%= link_to 'Preço Menor', products_findcategory_path(order: "price",categoryname: params[:categoryname]) %></li>
    <li><%= link_to 'Nome', products_findcategory_path(order: "name",categoryname: params[:categoryname]) %></li>
  </ul>
</div>
<br><br>

<div class="container">
  <% @products.each do |product| %>
    <% if logged_in? %>
      <% if product.sellable? || current_user.admin? %>  
      

      <div class="product_square col-md-3">
        <img src="http://worldartsme.com/images/shop-cart-icon-clipart-1.jpg" />
        <h3><%= product.name %></h3>
        <p><%= product.description %></p>
        <div align="right"><strong>R$</strong> <input type="text" class="fieldQty" value="<%= '%.2f'%(product.price) %>" style="text-align: center" size="6" readonly/></div>
        <% if current_user.admin? %>
                  <p><%= link_to '<i class="glyphicon glyphicon-edit"></i> Editar'.html_safe,edit_product_path(product.id),class: "btn btn-primary" %></p>
                  <p>Produto Vendível? <%= product.sellable.to_s.capitalize %></p>
                  <% else %>
                  <p><%= link_to '<i class="glyphicon glyphicon-shopping-cart"></i> Comprar'.html_safe,{:controller => "carts", :action => "addtocart",:product => product.id,:cart => current_cart,:quantity => 1},class: "btn btn-primary" %>
                  <% end %></p>
      </div>         
      <% end %>
    <% else %>
      <% if product.sellable? %>
      <div class="product_square col-md-3">
        <img src="http://worldartsme.com/images/shop-cart-icon-clipart-1.jpg" />
        <h3><%= product.name %></h3>
        <p><%= product.description %></p>
        <div align="right"><strong>R$</strong> <input type="text" class="fieldQty" value="<%= '%.2f'%(product.price) %>" style="text-align: center" size="6" readonly/></div>
        <p><% if logged_in? && current_user.admin? %>
                  <%= link_to '<i class="glyphicon glyphicon-edit"></i> Editar'.html_safe,edit_product_path(product.id),class: "btn btn-primary" %>
                  <% else %>
                  <%= link_to '<i class="glyphicon glyphicon-shopping-cart"></i> Comprar'.html_safe,{:controller => "carts", :action => "addtocart",:product => product.id,:cart => current_cart,:quantity => 1},class: "btn btn-primary" %>
                  <% end %></p>
      </div>         
      <% end %>
    <% end %>
  <%end%>
</div>

app/views/products/cafedamanha.html.erb
<h1> Café da Manhã </h1>
<%= render 'productsform' %>

app/views/products/carros.html.erb
<h1> Carros </h1>
<%= render 'productsform' %>

app/views/products/condimentos.html.erb
<h1> Condimentos </h1>
<%= render 'productsform' %>

app/views/products/edit.html.erb
<h1>Editar produto</h1>
<%= render 'formproducts' %>

app/views/products/findcategory.html.erb
<h1> Produtos (<%= params[:categoryname].capitalize %>) </h1>
<%= render 'productsform' %>

app/views/products/index.html.erb
<h1> Produtos </h1>

<%= render 'productsform' %>

app/views/products/new.html.erb
<h1>Criar Novo Produto</h1>
<%= render 'formproducts2' %>

app/views/products/search.html.erb
<h1>Pesquisa</h1>
<table class="table table-hover">
     <thead >
       <tr>
         <th>Nome</th>
         <th>Preço</th>
         
       </tr>
     </thead>
     <tbody>
       <% @products.each do |product| %>
         <tr>
           <td><%= product.name %></td>
           <td>R$ <%= product.price %></td>
         </tr>
      <%end%>
    </tbody>
 </table>
<%= link_to 'Voltar',products_path,class: "btn btn-primary" %>