config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'pages/home'
  get 'pages/perfil'
  get 'pages/troll'
  get 'pages/admin'
  get 'products/index'
  get 'products/condimentos'
  get 'products/cafedamanha'
  get 'products/carros'
  get 'products/findcategory'
  get 'products/addtocart'
  get 'products/search'
  get 'products/new'
  get 'carrinho/show' => 'carrinho#show'
  resources :categories
  resources :products
  resources :orders

  get 'orders/details/:id' => 'orders#detail'
  post 'orders/alterstatus'
  get 'carts/limpar'
  get 'carts/addtocart'
  get 'carts/aumentarqtd'
  get 'carts/diminuirqtd'
  get 'carts/destroy'
  post 'carts/destroy'
  get 'carts/remove'
  get 'carts/rise'
  get 'carts/low'
  post 'carts/rise'
  post 'carts/low'
  post 'carts/show' => 'carts#show'
  resources :carts,only: [:show]
  get 'users/new'
  resources :users

  get 'pages/home'
  root 'pages#home'
	get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :protegories, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	acts_as_shopping_cart_using :cart_item
	#comentario aleatorio
	#outro comentario
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	acts_as_shopping_cart_item_for :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :protegories
	has_many :products, through: :protegories
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :protegories
	has_many :categories, through: :protegories
	validates :name,presence: true, length: {maximum: 50}
	validates :price,presence: true
	validates :description, presence: true
	def self.search(search)
	  where("name ILIKE ?", "%#{search}%") 
	  #where("content LIKE ?", "%#{search}%")
	end
end

app/models/protegory.rb
class Protegory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :orders,dependent: :destroy
	validates :name,presence: true, length: {maximum: 50}
	validates :password,presence: true, length: {minimum: 6}
	VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
 	validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  	before_save { self.email = email.downcase }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	

	def addtocart
		#cart = current_cart
		@products = Product.find(params[:product])
		if (!current_cart.empty? && current_cart.any?{|h| h["product_id"] == @products.id})
			flash[:danger] = "Produto já consta no carrinho"
		else
			current_cart << {product_id: @products.id,quantity: 1,price: @products.price}
			flash[:success] = "Produto adicionado"
		end
		redirect_to :back
	end
	def remove
		@products = Product.find(params[:product])
		current_cart.delete_if{|h| h["product_id"] == @products.id}

		redirect_to carts_show_path
	end

	def rise
		@product = Product.find(params[:product])
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		h["quantity"] += 1
		 	end
		end
		respond_to do |format|
			format.html{ redirect_to carts_show_path}
			
			format.js
		end
		#redirect_to carts_show_path
		
	end
	def low
		@product = Product.find(params[:product])
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		if h["quantity"] != 0
		 			h["quantity"] -= 1
		 		end
		 	end
		end
		respond_to do |format|
			format.html{ redirect_to carts_show_path}
			
			format.js
		end
		#redirect_to carts_show_path
		
	end

	def destroy
		current_cart.clear
		redirect_to carts_show_path
	end

	def show
		@products = []
		if (!current_cart.empty?)
			current_cart.each do |h|
				pr = Product.find(h["product_id"])
				@products << {:id => pr.id,:name => pr.name,:description => pr.description,:price => pr.price,:quantity => h["quantity"]}
				#@products << h["product_id"]
			end
		end
		@cart = current_cart
		@total = 0
		current_cart.each do |h|
			@total += h["quantity"]*h["price"]
		end
		@total
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def categories
    	@categories = Category.all
  	end
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
	def session_cart
        session[:cart] = []
    end

     def current_cart
            @current_cart = Cart.find(5)
            #@current_cart ||= []
            
     end

end

app/helpers/carts_helper.rb
module CartsHelper

    def current_cart
        session[:cart] ||= []
    end
	def rise(idd)
		@product = Product.find(idd)
		current_cart.map do |h|
		 	if h["product_id"] == @product.id
		 		h["quantity"] += 1
		 	end
		end
	end
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/protegories_helper.rb
module ProtegoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	 def sign_in 
         session[:user_id] = @user.id
     end

     def current_user
            @current_user ||= User.find_by(id: session[:user_id])
     end

     #def current_cart
     #       session[:cart] ||= []
     #end

     def cart_in
        #se o usuario entrar, entao o carrinho vira o carrinho dele
     end
     def block_access
            if current_user.present?
                redirect_to users_path
            end
     end

     def logged_in?
     	!current_user.nil?
     end

     def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <strong><%= link_to 'DinnerDash1',root_path,class: "navbar-brand" %></strong>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <% @user = current_user %>
        <li><%= link_to '<i class="glyphicon glyphicon-list-alt"></i> Pedidos'.html_safe,order_path(current_user),method: "GET" %></li>
        <li><% if current_user.admin? %>
            <%= link_to '<i class="glyphicon glyphicon-wrench"></i> Admin'.html_safe,pages_admin_path %>
            <% end %>
            </li>
        <% else %>
          
        <% end %>
        <li class="dropdown">
          <a href="/products/index" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-th-list"></span> Produtos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% categories.each do |cat| %>
              <li><%= link_to "<i class=\"glyphicon glyphicon-tag\"></i>  #{cat.name.capitalize}".html_safe,products_findcategory_path(categoryname: cat.name) %></li>
            <% end %>
              
            <li role="separator" class="divider"></li>
            <li><%= link_to '<i class="glyphicon glyphicon-list"></i> Todos'.html_safe, products_index_path %></li>
            
          </ul>
        </li>
      </ul>
      
        <%= form_tag(products_search_path, :method => "GET",:html => {:id =>'form_id'},class: "navbar-form navbar-left") do %>

        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Procurar um produto",class: "form-control" %>
        </div>
          <%= button_tag(type: 'submit',name: nil, class: "btn btn-primary btn-sm") do %>
              <span class="glyphicon glyphicon-search"></span> 
          <% end %>
          
        <% end %>
    
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to '<i class="glyphicon glyphicon-cog"></i> Opções'.html_safe,edit_user_path(current_user) %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-log-out"></i> Logout'.html_safe,sign_out_path,method: "delete" %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> Perfil'.html_safe,user_path(current_user) %></li>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Login'.html_safe,sign_in_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-user"></i> Cadastro'.html_safe,new_user_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-shopping-cart"></span> Compras <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to '<i class="glyphicon glyphicon-shopping-cart"></i> Carrinho'.html_safe,carts_show_path%></li>
            <li><% if logged_in? %>
                <%=link_to '<i class="glyphicon glyphicon-ok"></i> Finalizar Compra'.html_safe,orders_path(owner_id: current_user.id,status: 2,date: Date.today,items: current_cart),method: "POST",data: {confirm: "Quer mesmo finalizar a compra?"} %>
                <% else %>
                <%= link_to '<i class="glyphicon glyphicon-ok"></i> Entre para Finalizar'.html_safe,sign_in_path %>
                <% end %> 
            </li>
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    
  	<%= render 'layouts/navigation' %>
    <div class="container">	
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
        </div>
          
      <% end %>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/pages/_login.html.erb
<div class="login-form">
  <h2>Login</h2>
  <br>

  <%= form_for :session, url: sign_in_path do |f| %>
      
      <div class="form-group has-feedback">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true,class: "form-control login-form-control",placeholder: "Email" %><i class="glyphicon glyphicon-user form-control-feedback"></i>
      </div>
     
      <div class="form-group has-feedback">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off",class: "form-control login-form-control",placeholder: "Password" %><i class="glyphicon glyphicon-lock form-control-feedback"></i>
      </div>
      <div class="actions">
        <%= f.submit "Log in" ,class: "log-btn"%>
      </div>
    <br>
    <p>Esqueceu a senha? <%= link_to 'Recuperar',"#" %></p>
    <p>Novo usuário? <%= link_to "Cadastre-se já!", new_user_path %></p>
  <% end %>
</div>

app/views/pages/_lorem.html.erb
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. In ipsum illum, rem necessitatibus quia explicabo vero autem laborum voluptatem reiciendis ut tempora nihil ea alias nemo vitae consequatur eius, asperiores.</p>
  <hr class="my-4">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem nisi alias eius mollitia laudantium repellat omnis et aliquam, in error commodi, blanditiis ipsa aliquid fuga suscipit minima! Quos, sapiente, doloremque.</p>
  <p class="lead">
    
    <%= link_to 'Não Aperte',pages_troll_path,class: "btn btn-primary btn-lg",role: "button" %>
  </p>

app/views/pages/admin.html.erb
<h1>Página do Admin</h1>
<br>

<div class="list-group">
  <%= link_to 'Criar Item', new_product_path,class: "list-group-item" %>
  <%= link_to 'Editar Item',products_path,class: "list-group-item" %> 
  <%= link_to 'Criar Categoria',new_category_path,class: "list-group-item" %>  
  <%= link_to 'Verificar Categorias',categories_path,class: "list-group-item" %>  
  <%= link_to 'Verificar Pedidos',orders_path,class: "list-group-item" %>  
 
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div>
  	<h1 class="display-3" align="center">Welcome to Dinner Dash 1</h1>
  </div>
 	 <div>
	  <% if logged_in? %>
		<%= render 'lorem' %>
	  <% else %>
	  	<%= render 'login' %>
		<% end %>
	</div>
</div>

app/views/pages/perfil.html.erb
<h1>Perfil do Usuário</h1>

app/views/pages/troll.html.erb
<h1>Falei para não apertar...</h1>